name: "Community Event Submission"
description: "Submit an event to share with the community"
title: "[Community Event] <Your Event Title>"
labels: ["community", "pending"]
assignees: []
body:
  - type: input
    id: title
    attributes:
      label: "Event Title"
      placeholder: "Youth fishing event"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: "Event Date/Time (ISO8601 UTC, ends with Z)"
      placeholder: "2026-03-15T23:59:00Z"
      description: |
        Use Zulu (UTC) time in ISO8601 format. Examples:
        - 2026-03-15T23:59:00Z  (March 15, 2026 at 23:59 UTC)
        - 2026-11-01T05:00:00Z  (Nov 1, 2026 at 05:00 UTC)

        Quick rules:
        - Include the letter 'T' between date and time.
        - End with 'Z' to indicate UTC (Zulu).
        - Use 24-hour time (00–23).
        - Include seconds (e.g., :00).
    validations:
      required: true

  - type: input
    id: state
    attributes:
      label: "State (Full name)"
      placeholder: "Ohio"
    validations:
      required: true

  - type: input
    id: county
    attributes:
      label: "County"
      placeholder: "Franklin"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: "Type"
      options:
        - "hunting"
        - "fishing"
        - "other"
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: "Notes (optional)"
      placeholder: "Bring your own gear."
    validations:
      required: false
