name: Community Event Submission
description: Submit a hunting, fishing, or outdoor community event
title: "[Event]: "
labels: ["community", "pending"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a community event! Please fill out the form below.
        
        **Note:** Events will be reviewed before appearing in the app. They must include all required fields.
  
  - type: input
    id: title
    attributes:
      label: Event Title
      description: Short, descriptive name of the event
      placeholder: e.g., "Youth Fishing Derby" or "Deer Draw Application Deadline"
    validations:
      required: true
  
  - type: input
    id: date
    attributes:
      label: Event Date
      description: Use format YYYY-MM-DD or MM/DD/YYYY
      placeholder: e.g., 2026-03-15 or 03/15/2026
    validations:
      required: true
  
  - type: input
    id: state
    attributes:
      label: State
      description: Full state name
      placeholder: e.g., Ohio
    validations:
      required: true
  
  - type: input
    id: county
    attributes:
      label: County
      description: County where the event takes place
      placeholder: e.g., Franklin
    validations:
      required: true
  
  - type: dropdown
    id: type
    attributes:
      label: Event Type
      description: Select the type of event
      options:
        - hunting
        - fishing
        - other
    validations:
      required: true
  
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any extra details or instructions (optional)
      placeholder: e.g., "Bring your own gear" or "Registration required"
    validations:
      required: false
